### ISSUE TITLE
worker prints empty newlines

### ISSUE THREAD

**Issue by JuliusNmn** [yjs/y-redis#33]
**Checklist**

* [X] Are you reporting a bug? Use github issues for bug reports and feature requests. For general questions, please use https://discuss.yjs.dev/
* [X] Try to report your issue in the correct repository. Yjs consists of many modules. When in doubt, report it to https://github.com/yjs/yjs/issues/

**Describe the bug**
The y-redis script keeps printing empty newlines, 1 every second, forever

```
worker-1          | using s3 store
y-redis-server-1  | using s3 store
worker-1          | 
worker-1          | 
y-redis-server-1  | 
worker-1          | 
worker-1          | 
worker-1          | 
worker-1          | 
worker-1          | 
worker-1          | 
worker-1          | 
```

**To Reproduce**
I'm starting y-redis through docker compose, like this:

```
y-redis-server:
    build: ./y-redis
    ports:
      - "3002:3002"
    command: node ./bin/server.js --no-colors
    env_file: .env
    depends_on:
      - minio
      - redis-server
    networks:
      - app-network
  worker:
    build: ./y-redis
    command: node ./bin/worker.js --no-colors
    env_file: .env
    depends_on:
      - minio
      - redis-server
    networks:
      - app-network
      
```

**Expected behavior**
Logs should 

**Screenshots**

**Environment Information**
y-redis 0.1.6
Docker version 27.2.0, build 3ab4256

**Additional context**

* [ ] I'm a sponsor 💖
* [ ] This issue is a blocker for my project.
